[2025-08-13T12:10:07.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_data manual__2025-08-13T12:10:05.466357+00:00 [queued]>
[2025-08-13T12:10:07.289+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.extract_data manual__2025-08-13T12:10:05.466357+00:00 [queued]>
[2025-08-13T12:10:07.293+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-08-13T12:10:07.361+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-08-13 12:10:05.466357+00:00
[2025-08-13T12:10:07.380+0000] {standard_task_runner.py:57} INFO - Started process 325 to run task
[2025-08-13T12:10:07.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'extract_data', 'manual__2025-08-13T12:10:05.466357+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmphx_q4ktg']
[2025-08-13T12:10:07.409+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask extract_data
[2025-08-13T12:10:07.470+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-13T12:10:07.619+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_etl_pipeline.extract_data manual__2025-08-13T12:10:05.466357+00:00 [running]> on host 1d02f9b6d307
[2025-08-13T12:10:07.974+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T12:10:05.466357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T12:10:05.466357+00:00'
[2025-08-13T12:10:08.012+0000] {logging_mixin.py:151} INFO - Error reading CSV: 'date'
[2025-08-13T12:10:08.022+0000] {python.py:194} INFO - Done. Returned value was: Empty DataFrame
Columns: []
Index: []
[2025-08-13T12:10:08.162+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=extract_data, execution_date=20250813T121005, start_date=20250813T121007, end_date=20250813T121008
[2025-08-13T12:10:08.225+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-13T12:10:08.320+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
